add utility for browsing and removing messages for dlq
CJSCommonPlatform/test-utils pull request #4
Opened 2017-05-18 11:00 UTC by Iamfrenzy

2017-05-18 11:49 UTC, allanmckenzie commented on test-utils-core/src/main/java/uk/gov/justice/services/test/utils/core/messaging/DlqMessageClient.java
> +    public DlqMessageClient(QueueConnection connection, Session session, Queue dlqQueue, String dlqName,
parameters should be final

2017-05-18 11:51 UTC, allanmckenzie commented on test-utils-core/src/main/java/uk/gov/justice/services/test/utils/core/messaging/QueueUriProvider.java
>      }
I'm afraid you can't change this - there are a lot of integration tests that rely on getting the correct url to speak to the deployed app. You'll need to create another class or method

2017-05-18 11:52 UTC, allanmckenzie commented on test-utils-core/src/main/java/uk/gov/justice/services/test/utils/core/messaging/DlqMessageClient.java
> +            sleeper.sleepFor(200);
Not sure sleep is a good idea here.

2017-05-18 11:52 UTC, allanmckenzie commented on test-utils-core/src/main/java/uk/gov/justice/services/test/utils/core/messaging/DlqMessageClient.java
> +            Enumeration enumeration = dlqBrowser.getEnumeration();
final

2017-05-18 11:52 UTC, allanmckenzie commented on test-utils-core/src/main/java/uk/gov/justice/services/test/utils/core/messaging/DlqMessageClient.java
> +            throw new RuntimeException(e);
put the error message into the exception

2017-05-18 13:16 UTC, purple52 requested changes
This appears to replicate a lot of the code in the main MessageConsumerClient, and does its own connection creation, etc. I would prefer this to reuse the existing client code (refactored/extended where appropriate). We also need examples for use cases in the class Javadocs and Javadocs for all public methods. Please come and talk to us and perhaps pair with one of us to produce a plan for how to integrate these classes.

2017-05-18 13:44 UTC, Iamfrenzy commented on test-utils-core/src/main/java/uk/gov/justice/services/test/utils/core/messaging/DlqMessageClient.java
> +    public DlqMessageClient(QueueConnection connection, Session session, Queue dlqQueue, String dlqName,
done

2017-05-18 13:44 UTC, Iamfrenzy commented on test-utils-core/src/main/java/uk/gov/justice/services/test/utils/core/messaging/QueueUriProvider.java
>      }
done

2017-05-18 13:44 UTC, Iamfrenzy commented on test-utils-core/src/main/java/uk/gov/justice/services/test/utils/core/messaging/DlqMessageClient.java
> +            sleeper.sleepFor(200);
done

2017-05-18 13:44 UTC, Iamfrenzy commented on test-utils-core/src/main/java/uk/gov/justice/services/test/utils/core/messaging/DlqMessageClient.java
> +            Enumeration enumeration = dlqBrowser.getEnumeration();
done

2017-05-24 14:29 UTC, purple52 requested changes
I've added one comment to the code. Also please check code coverage; Coveralls is reporting it has dropped by 1.6%.
Before merge, we'll need to squash your commits into one. If you know how to do that please go for it. Otherwise, I can do it when I merge.

2017-05-24 14:29 UTC, purple52 commented on test-utils-core/src/main/java/uk/gov/justice/services/test/utils/core/messaging/DeadLetterQueueBrowser.java
> +    private void doClose(final AutoCloseable closeable) {
Is this still used? If not, it should be removed

2017-05-24 16:31 UTC, purple52 approved these changes

2017-05-24 16:39 UTC, merged